version: '3.9'

services:
  mosquitto1:
    build: .
    image: gw1-ssh  
    container_name: gw1
    ports:
      - "1884:1883"
      - "2221:22"     # SSH for 1
    volumes:
      - ./mqtt-brokers/broker1/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - loranet

  mosquitto2:
    build: .
    image: gw2-ssh
    container_name: gw2
    ports:
      - "1885:1883"
      - "2222:22"     # SSH for 2
    volumes:
      - ./mqtt-brokers/broker2/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - loranet

  mosquitto3:
    build: .
    image: gw3-ssh
    container_name: gw3
    ports:
      - "1886:1883"
      - "2223:22"     # SSH for 3
    volumes:
      - ./mqtt-brokers/broker3/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - loranet
  
networks:
  loranet:
    ipam:
      config:
        - subnet: 192.168.10.0/24
    driver: bridge
